### PR TITLE
seanaye/chore/pull upstream

### PR DESCRIPTION
**Pull request by seanaye**
Pull in upstream changes.

I think I did properly

### CODE REVIEW

**Comment by chase** [comment]
@seanaye Based on what I see amongst the massive amount of changes, they essentially did a rewrite on some parts and moved a lot of files into other portions so changes that we've made to will no longer exist in the proper place (as they are considered new files), including the glyph positions.

This will also likely affect some types used in our app, since the JSDoc signatures are used to generate the typescript used.

The net result of the changes we've made can be seen here:
https://github.com/mozilla/pdf.js/compare/master...coparse-inc:pdf.js:master

We need to ensure that these changes are ported over correctly. After they are ported, functionality reliant on our changes still function correctly, namely:
- Creating highlights with the correct text visible in the sidebar
- Loading existing highlights with the correct text visible in the sidebar
- Search functionality including:
  - Match result previews in the sidebar contain the correct text
  - Jumping to matches by using the up/down arrow keys
  - Jumping to matches by clicking on a match

Once this functionality has been QA'd and general PDF behavior functions correctly, I think it's relatively safe to move forward with the PDF.js-based decryption.

**Comment by chase** [comment]
It's also worth noting that some functionality that we use to remove flickering when selecting text is permanently removed upstream:
https://github.com/mozilla/pdf.js/pull/15259

It's worth checking if selecting text across multiple paragraphs with sizable gaps between them flickers in this updated version, because we might have to figure out a better fix than simply re-integrating the `enhanceTextSelection` functionality.

That said, I feel like probably just adding enhanceTextSelection back into the code is the right fix, but introduces a greater maintenance burden long term as things diverge.

---

It seems that it certainly makes Chromium-based selection less pleasant, and the alternative textLayerMode mentioned also no longer exists:
https://github.com/mozilla/pdf.js/issues/9843#issuecomment-1030720809

Demonstration of said issue in latest version: https://github.com/mozilla/pdf.js/issues/15733

**Comment by chase** [comment]
Also of note, there are likely changes that were done to the find controller. We extend and override the find controller class here:
https://github.com/coparse-inc/app-monorepo/blob/master/packages/app/src/pdfViewer/FindController.ts#L50-L169

The methods that have been overridden to support our functionality may have to be changed.

**Comment by chase** [comment]
[8b23f6b](https://github.com/coparse-inc/pdf.js/pull/2/commits/8b23f6b01832b7db4ad323d03a8815362b6304ff) looks like you wanted to drop this before merge? @seanaye

**Comment by seanaye** [comment]
@chase yea, not done yet I've been working on release stuff. The commit has been kinda "dropped" since the changes were reverted in later commits anyway. I'll do it properly tmr tho

**Comment by chase** [comment]
Closed in favor of #3

**Pull request closed without merging**
