### PR TITLE
Pull upstream v2.16.105

### PR DESCRIPTION
**Pull request by chase**
Instead of pulling in the latest version of the `master` branch upstream, we can pull the last API-compatible version.

- This avoids having to backport `enhanceTextSelection`
- This includes most of the editor goodies
- This does not include any of the text layer optimizations

### CODE REVIEW

**Review by seanaye — APPROVED** [review]
yay minimal text_layer changes

**Review by seanaye — CHANGES_REQUESTED** [review]
This is broken as-is, will fix. Invalidating my previous approval so nobody merges

**Review by seanaye — APPROVED** [review]
All required changes are integration changes inside our app for new parameter types

**Comment by awallace** [comment]
cc @chase @seanaye this was just about ready to go - there is one small tweak to our override of `createTextLayerBuilder` that gets everything working in monorepo. Once this lands I will tag this and bump monorepo tagged version in that PR [ https://github.com/coparse-inc/app-monorepo/pull/1663 ]

And then once these are landed I'll move the annotation PR on top of this and can get some extra annotation goodies out of the Annotation API. I'm planning to do that in a separate PR and tagged version of pdfjs, so this can bake in the oven on its own before too many extra changes get added.

Please LMK what you think cc @chase @seanaye

**Comment by chase** [comment]
> cc @chase @seanaye this was just about ready to go - there is one small tweak to our override of `createTextLayerBuilder` that gets everything working in monorepo. Once this lands I will tag this and bump monorepo tagged version in that PR [ https://github.com/[coparse-inc/app-monorepo/pull/1663](https://github.com/coparse-inc/app-monorepo/pull/1663) ]
> 
> And then once these are landed I'll move the annotation PR on top of this and can get some extra annotation goodies out of the Annotation API. I'm planning to do that in a separate PR and tagged version of pdfjs, so this can bake in the oven on its own before too many extra changes get added.
> 
> Please LMK what you think cc @chase @seanaye

@awallace Sean made a PR a long while back covering that change and a few other necessary changes: https://github.com/coparse-inc/app-monorepo/pull/1375

I cannot recall if there other minor features that left that PR in draft or if we just got too busy. Either way, might be better to mark Sean's PR as ready and get it merged.

**Comment by seanaye** [comment]
There were no other features it's just to add compat for latest v2

**Comment by awallace** [comment]
Gotcha - then let's get this pdfjs update in and tagged, and then I'll update the compat PR with the new tag and we're good to go. Thanks!

**Pull request merged**
